"""add_preprocessing_schema

Revision ID: 95646b91a327
Revises: bb7381a5682c
Create Date: 2026-07-17 23:48:41.157385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95646b91a327'
down_revision: Union[str, None] = 'bb7381a5682c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_preprocessing',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('preprocessed_dataset_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('pipeline_version', sa.Integer(), nullable=False),
    sa.Column('preprocessing_hash', sa.String(length=64), nullable=False),
    sa.Column('python_version', sa.String(length=50), nullable=False),
    sa.Column('pandas_version', sa.String(length=50), nullable=False),
    sa.Column('numpy_version', sa.String(length=50), nullable=False),
    sa.Column('sklearn_version', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preprocessed_dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_preprocessing_dataset_id'), 'dataset_preprocessing', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_preprocessing_id'), 'dataset_preprocessing', ['id'], unique=False)
    op.create_index(op.f('ix_dataset_preprocessing_preprocessed_dataset_id'), 'dataset_preprocessing', ['preprocessed_dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_preprocessing_preprocessing_hash'), 'dataset_preprocessing', ['preprocessing_hash'], unique=False)
    op.create_index(op.f('ix_dataset_preprocessing_project_id'), 'dataset_preprocessing', ['project_id'], unique=False)
    op.create_index(op.f('ix_dataset_preprocessing_status'), 'dataset_preprocessing', ['status'], unique=False)
    op.create_index(op.f('ix_dataset_preprocessing_user_id'), 'dataset_preprocessing', ['user_id'], unique=False)
    op.create_table('feature_metadata',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('feature_type', sa.String(length=50), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('encoded', sa.Boolean(), nullable=False),
    sa.Column('scaled', sa.Boolean(), nullable=False),
    sa.Column('generated', sa.Boolean(), nullable=False),
    sa.Column('target', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_metadata_dataset_id'), 'feature_metadata', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_feature_metadata_feature_type'), 'feature_metadata', ['feature_type'], unique=False)
    op.create_index(op.f('ix_feature_metadata_id'), 'feature_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_feature_metadata_target'), 'feature_metadata', ['target'], unique=False)
    op.create_table('preprocessing_artifacts',
    sa.Column('preprocessing_run_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preprocessing_run_id'], ['dataset_preprocessing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preprocessing_artifacts_artifact_type'), 'preprocessing_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_preprocessing_artifacts_checksum'), 'preprocessing_artifacts', ['checksum'], unique=False)
    op.create_index(op.f('ix_preprocessing_artifacts_id'), 'preprocessing_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_preprocessing_artifacts_preprocessing_run_id'), 'preprocessing_artifacts', ['preprocessing_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preprocessing_artifacts_preprocessing_run_id'), table_name='preprocessing_artifacts')
    op.drop_index(op.f('ix_preprocessing_artifacts_id'), table_name='preprocessing_artifacts')
    op.drop_index(op.f('ix_preprocessing_artifacts_checksum'), table_name='preprocessing_artifacts')
    op.drop_index(op.f('ix_preprocessing_artifacts_artifact_type'), table_name='preprocessing_artifacts')
    op.drop_table('preprocessing_artifacts')
    op.drop_index(op.f('ix_feature_metadata_target'), table_name='feature_metadata')
    op.drop_index(op.f('ix_feature_metadata_id'), table_name='feature_metadata')
    op.drop_index(op.f('ix_feature_metadata_feature_type'), table_name='feature_metadata')
    op.drop_index(op.f('ix_feature_metadata_dataset_id'), table_name='feature_metadata')
    op.drop_table('feature_metadata')
    op.drop_index(op.f('ix_dataset_preprocessing_user_id'), table_name='dataset_preprocessing')
    op.drop_index(op.f('ix_dataset_preprocessing_status'), table_name='dataset_preprocessing')
    op.drop_index(op.f('ix_dataset_preprocessing_project_id'), table_name='dataset_preprocessing')
    op.drop_index(op.f('ix_dataset_preprocessing_preprocessing_hash'), table_name='dataset_preprocessing')
    op.drop_index(op.f('ix_dataset_preprocessing_preprocessed_dataset_id'), table_name='dataset_preprocessing')
    op.drop_index(op.f('ix_dataset_preprocessing_id'), table_name='dataset_preprocessing')
    op.drop_index(op.f('ix_dataset_preprocessing_dataset_id'), table_name='dataset_preprocessing')
    op.drop_table('dataset_preprocessing')
    # ### end Alembic commands ###
