"""add_monitoring_tables

Revision ID: b52b022d585c
Revises: 1e5b624ce287
Create Date: 2026-07-18 21:11:54.817413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52b022d585c'
down_revision: Union[str, None] = '1e5b624ce287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_health_logs',
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('database_healthy', sa.Boolean(), nullable=False),
    sa.Column('storage_healthy', sa.Boolean(), nullable=False),
    sa.Column('cache_healthy', sa.Boolean(), nullable=False),
    sa.Column('worker_healthy', sa.Boolean(), nullable=False),
    sa.Column('response_latency_ms', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_health_logs_id'), 'monitoring_health_logs', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_health_logs_recorded_at'), 'monitoring_health_logs', ['recorded_at'], unique=False)
    op.create_table('monitoring_job_locks',
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('lease_owner', sa.Uuid(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_name')
    )
    op.create_table('alert_rules',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('comparison_operator', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_alert_rules_project_id'), 'alert_rules', ['project_id'], unique=False)
    op.create_table('external_telemetry_logs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('provider_record_id', sa.String(length=100), nullable=True),
    sa.Column('ingestion_status', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('normalized_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_telemetry_logs_id'), 'external_telemetry_logs', ['id'], unique=False)
    op.create_index(op.f('ix_external_telemetry_logs_project_id'), 'external_telemetry_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_external_telemetry_logs_recorded_at'), 'external_telemetry_logs', ['recorded_at'], unique=False)
    op.create_table('drift_snapshots',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method_name', sa.String(length=50), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('is_drifted', sa.Boolean(), nullable=False),
    sa.Column('feature_drifts', sa.JSON(), nullable=False),
    sa.Column('target_drift', sa.JSON(), nullable=True),
    sa.Column('baseline_statistics_version', sa.String(length=64), nullable=False),
    sa.Column('algorithm_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='drift_status'), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['trained_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_snapshots_id'), 'drift_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_drift_snapshots_model_id'), 'drift_snapshots', ['model_id'], unique=False)
    op.create_index(op.f('ix_drift_snapshots_project_id'), 'drift_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_drift_snapshots_status'), 'drift_snapshots', ['status'], unique=False)
    op.create_table('monitoring_alerts',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status'), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['trained_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_alerts_id'), 'monitoring_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_alerts_model_id'), 'monitoring_alerts', ['model_id'], unique=False)
    op.create_index(op.f('ix_monitoring_alerts_project_id'), 'monitoring_alerts', ['project_id'], unique=False)
    op.create_index(op.f('ix_monitoring_alerts_rule_id'), 'monitoring_alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_monitoring_alerts_status'), 'monitoring_alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_alerts_status'), table_name='monitoring_alerts')
    op.drop_index(op.f('ix_monitoring_alerts_rule_id'), table_name='monitoring_alerts')
    op.drop_index(op.f('ix_monitoring_alerts_project_id'), table_name='monitoring_alerts')
    op.drop_index(op.f('ix_monitoring_alerts_model_id'), table_name='monitoring_alerts')
    op.drop_index(op.f('ix_monitoring_alerts_id'), table_name='monitoring_alerts')
    op.drop_table('monitoring_alerts')
    op.drop_index(op.f('ix_drift_snapshots_status'), table_name='drift_snapshots')
    op.drop_index(op.f('ix_drift_snapshots_project_id'), table_name='drift_snapshots')
    op.drop_index(op.f('ix_drift_snapshots_model_id'), table_name='drift_snapshots')
    op.drop_index(op.f('ix_drift_snapshots_id'), table_name='drift_snapshots')
    op.drop_table('drift_snapshots')
    op.drop_index(op.f('ix_external_telemetry_logs_recorded_at'), table_name='external_telemetry_logs')
    op.drop_index(op.f('ix_external_telemetry_logs_project_id'), table_name='external_telemetry_logs')
    op.drop_index(op.f('ix_external_telemetry_logs_id'), table_name='external_telemetry_logs')
    op.drop_table('external_telemetry_logs')
    op.drop_index(op.f('ix_alert_rules_project_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_table('monitoring_job_locks')
    op.drop_index(op.f('ix_monitoring_health_logs_recorded_at'), table_name='monitoring_health_logs')
    op.drop_index(op.f('ix_monitoring_health_logs_id'), table_name='monitoring_health_logs')
    op.drop_table('monitoring_health_logs')
    # ### end Alembic commands ###
