"""add_training_registry_schema

Revision ID: 1dca5f576489
Revises: 95646b91a327
Create Date: 2026-07-18 09:31:28.062147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dca5f576489'
down_revision: Union[str, None] = '95646b91a327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_experiments',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_experiments_id'), 'training_experiments', ['id'], unique=False)
    op.create_index(op.f('ix_training_experiments_project_id'), 'training_experiments', ['project_id'], unique=False)
    op.create_table('evaluation_reports',
    sa.Column('trained_model_id', sa.Uuid(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trained_model_id'], ['trained_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_reports_id'), 'evaluation_reports', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_reports_trained_model_id'), 'evaluation_reports', ['trained_model_id'], unique=False)
    op.create_table('hyperparameter_sets',
    sa.Column('trained_model_id', sa.Uuid(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trained_model_id'], ['trained_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hyperparameter_sets_id'), 'hyperparameter_sets', ['id'], unique=False)
    op.create_index(op.f('ix_hyperparameter_sets_trained_model_id'), 'hyperparameter_sets', ['trained_model_id'], unique=False)
    op.add_column('trained_models', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('trained_models', sa.Column('checksum', sa.String(length=64), nullable=True))
    op.add_column('trained_models', sa.Column('hyperparameters', sa.JSON(), nullable=True))
    op.add_column('trained_models', sa.Column('signature', sa.JSON(), nullable=True))
    op.add_column('trained_models', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trained_models', sa.Column('activated_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_trained_models_status'), 'trained_models', ['status'], unique=False)
    op.create_foreign_key(None, 'trained_models', 'users', ['activated_by'], ['id'], ondelete='SET NULL')
    op.add_column('training_sessions', sa.Column('experiment_id', sa.Uuid(), nullable=True))
    op.add_column('training_sessions', sa.Column('preprocessing_run_id', sa.Uuid(), nullable=True))
    op.add_column('training_sessions', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('training_sessions', sa.Column('config', sa.JSON(), nullable=True))
    op.add_column('training_sessions', sa.Column('training_seed', sa.Integer(), nullable=True))
    op.add_column('training_sessions', sa.Column('test_size', sa.Float(), nullable=True))
    op.add_column('training_sessions', sa.Column('shuffle', sa.Boolean(), nullable=True))
    op.add_column('training_sessions', sa.Column('stratify_column', sa.String(length=100), nullable=True))
    op.add_column('training_sessions', sa.Column('cv_seed', sa.Integer(), nullable=True))
    op.add_column('training_sessions', sa.Column('config_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_training_sessions_config_hash'), 'training_sessions', ['config_hash'], unique=False)
    op.create_index(op.f('ix_training_sessions_experiment_id'), 'training_sessions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_preprocessing_run_id'), 'training_sessions', ['preprocessing_run_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'training_sessions', 'training_experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'training_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'training_sessions', 'dataset_preprocessing', ['preprocessing_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_sessions', type_='foreignkey')
    op.drop_constraint(None, 'training_sessions', type_='foreignkey')
    op.drop_constraint(None, 'training_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_preprocessing_run_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_experiment_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_config_hash'), table_name='training_sessions')
    op.drop_column('training_sessions', 'config_hash')
    op.drop_column('training_sessions', 'cv_seed')
    op.drop_column('training_sessions', 'stratify_column')
    op.drop_column('training_sessions', 'shuffle')
    op.drop_column('training_sessions', 'test_size')
    op.drop_column('training_sessions', 'training_seed')
    op.drop_column('training_sessions', 'config')
    op.drop_column('training_sessions', 'user_id')
    op.drop_column('training_sessions', 'preprocessing_run_id')
    op.drop_column('training_sessions', 'experiment_id')
    op.drop_constraint(None, 'trained_models', type_='foreignkey')
    op.drop_index(op.f('ix_trained_models_status'), table_name='trained_models')
    op.drop_column('trained_models', 'activated_by')
    op.drop_column('trained_models', 'activated_at')
    op.drop_column('trained_models', 'signature')
    op.drop_column('trained_models', 'hyperparameters')
    op.drop_column('trained_models', 'checksum')
    op.drop_column('trained_models', 'status')
    op.drop_index(op.f('ix_hyperparameter_sets_trained_model_id'), table_name='hyperparameter_sets')
    op.drop_index(op.f('ix_hyperparameter_sets_id'), table_name='hyperparameter_sets')
    op.drop_table('hyperparameter_sets')
    op.drop_index(op.f('ix_evaluation_reports_trained_model_id'), table_name='evaluation_reports')
    op.drop_index(op.f('ix_evaluation_reports_id'), table_name='evaluation_reports')
    op.drop_table('evaluation_reports')
    op.drop_index(op.f('ix_training_experiments_project_id'), table_name='training_experiments')
    op.drop_index(op.f('ix_training_experiments_id'), table_name='training_experiments')
    op.drop_table('training_experiments')
    # ### end Alembic commands ###
