"""add_deployment_tables

Revision ID: c1e27c65460c
Revises: 097ac139b0de
Create Date: 2026-07-25 13:39:15.973210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e27c65460c'
down_revision: Union[str, None] = '097ac139b0de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_environments',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_environments_id'), 'deployment_environments', ['id'], unique=False)
    op.create_index(op.f('ix_deployment_environments_project_id'), 'deployment_environments', ['project_id'], unique=False)
    op.create_table('deployment_freeze_windows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time_utc', sa.Time(), nullable=False),
    sa.Column('end_day_of_week', sa.Integer(), nullable=False),
    sa.Column('end_time_utc', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_freeze_windows_project_id'), 'deployment_freeze_windows', ['project_id'], unique=False)
    op.create_table('deployment_policies',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('required_approvals', sa.Integer(), nullable=False),
    sa.Column('required_reviewer_roles', sa.String(length=100), nullable=True),
    sa.Column('maximum_latency_ms', sa.Float(), nullable=True),
    sa.Column('maximum_error_rate', sa.Float(), nullable=True),
    sa.Column('minimum_success_rate', sa.Float(), nullable=True),
    sa.Column('minimum_throughput', sa.Float(), nullable=True),
    sa.Column('minimum_health_checks', sa.Integer(), nullable=False),
    sa.Column('rollback_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('required_probe_types', sa.String(length=100), nullable=True),
    sa.Column('minimum_successful_probes', sa.Integer(), nullable=False),
    sa.Column('probe_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('parallel_execution', sa.Boolean(), nullable=False),
    sa.Column('promotion_stages', sa.JSON(), nullable=False),
    sa.Column('required_consecutive_successes', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('policy_checksum', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['deployment_policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_policies_id'), 'deployment_policies', ['id'], unique=False)
    op.create_index(op.f('ix_deployment_policies_project_id'), 'deployment_policies', ['project_id'], unique=False)
    op.create_table('deployment_settings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_interval', sa.Integer(), nullable=False),
    sa.Column('checkpoint_retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('deployment_job_locks',
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('lease_owner', sa.Uuid(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['deployment_environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('environment_id')
    )
    op.create_table('model_deployments',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('policy_version_id', sa.Uuid(), nullable=False),
    sa.Column('deployment_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('strategy', sa.String(length=30), nullable=False),
    sa.Column('traffic_percentage', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('artifact_repository', sa.String(length=255), nullable=True),
    sa.Column('artifact_digest', sa.String(length=128), nullable=True),
    sa.Column('artifact_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('artifact_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('artifact_signed_by', sa.String(length=100), nullable=True),
    sa.Column('manifest_version', sa.String(length=50), nullable=True),
    sa.Column('manifest_checksum', sa.String(length=64), nullable=True),
    sa.Column('manifest_schema_version', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['environment_id'], ['deployment_environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['trained_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['deployment_policies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_deployments_environment_id'), 'model_deployments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_model_deployments_id'), 'model_deployments', ['id'], unique=False)
    op.create_index(op.f('ix_model_deployments_model_id'), 'model_deployments', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_deployments_policy_version_id'), 'model_deployments', ['policy_version_id'], unique=False)
    op.create_index(op.f('ix_model_deployments_project_id'), 'model_deployments', ['project_id'], unique=False)
    op.create_index(op.f('ix_model_deployments_status'), 'model_deployments', ['status'], unique=False)
    op.create_table('deployment_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reviewer_order', sa.Integer(), nullable=False),
    sa.Column('approval_stage', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.Column('approval_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['model_deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_approvals_deployment_id'), 'deployment_approvals', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_approvals_reviewer_id'), 'deployment_approvals', ['reviewer_id'], unique=False)
    op.create_table('deployment_environment_variables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('encrypted_value', sa.String(), nullable=True),
    sa.Column('secret_reference', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['model_deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_environment_variables_deployment_id'), 'deployment_environment_variables', ['deployment_id'], unique=False)
    op.create_table('deployment_event_checkpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('last_sequence_number', sa.Integer(), nullable=False),
    sa.Column('checkpoint_hash', sa.String(length=128), nullable=False),
    sa.Column('snapshot', sa.LargeBinary(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('compression', sa.String(length=20), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=20), nullable=False),
    sa.Column('snapshot_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_from_sequence', sa.Integer(), nullable=False),
    sa.Column('checkpoint_format_version', sa.Integer(), nullable=False),
    sa.Column('checkpoint_serializer', sa.String(length=30), nullable=False),
    sa.Column('serializer_version', sa.String(length=50), nullable=True),
    sa.Column('backend_version', sa.String(length=50), nullable=True),
    sa.Column('python_runtime', sa.String(length=50), nullable=True),
    sa.Column('decompressed_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checkpoint_duration_ms', sa.Float(), nullable=False),
    sa.Column('created_by_instance', sa.String(length=100), nullable=True),
    sa.Column('hash_algorithm_version', sa.String(length=20), nullable=True),
    sa.Column('checkpoint_signature', sa.String(length=256), nullable=True),
    sa.Column('signature_algorithm', sa.String(length=50), nullable=True),
    sa.Column('signing_key_id', sa.String(length=100), nullable=True),
    sa.Column('encryption_algorithm', sa.String(length=50), nullable=True),
    sa.Column('encryption_key_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['model_deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_event_checkpoints_deployment_id'), 'deployment_event_checkpoints', ['deployment_id'], unique=False)
    op.create_table('deployment_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_version', sa.String(length=10), nullable=False),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('previous_state', sa.String(length=30), nullable=True),
    sa.Column('new_state', sa.String(length=30), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload_version', sa.String(length=10), nullable=False),
    sa.Column('replayable', sa.Boolean(), nullable=False),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=True),
    sa.Column('current_event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['model_deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_events_current_event_hash'), 'deployment_events', ['current_event_hash'], unique=False)
    op.create_index(op.f('ix_deployment_events_deployment_id'), 'deployment_events', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_events_sequence_number'), 'deployment_events', ['sequence_number'], unique=False)
    op.create_table('deployment_health_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cpu_usage_pct', sa.Float(), nullable=False),
    sa.Column('memory_usage_mb', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('throughput_rps', sa.Float(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deployment_duration_ms', sa.Integer(), nullable=False),
    sa.Column('startup_time_ms', sa.Integer(), nullable=False),
    sa.Column('container_ready_time', sa.Integer(), nullable=False),
    sa.Column('traffic_shift_duration', sa.Integer(), nullable=False),
    sa.Column('rollback_duration', sa.Integer(), nullable=False),
    sa.Column('health_probe_count', sa.Integer(), nullable=False),
    sa.Column('successful_probe_count', sa.Integer(), nullable=False),
    sa.Column('failed_probe_count', sa.Integer(), nullable=False),
    sa.Column('estimated_cpu_cost', sa.Float(), nullable=False),
    sa.Column('estimated_memory_cost', sa.Float(), nullable=False),
    sa.Column('estimated_runtime_cost', sa.Float(), nullable=False),
    sa.Column('estimated_network_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['model_deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_health_logs_deployment_id'), 'deployment_health_logs', ['deployment_id'], unique=False)
    op.create_table('deployment_manifest_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('manifest_version', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('artifact_checksum', sa.String(length=64), nullable=False),
    sa.Column('model_checksum', sa.String(length=64), nullable=False),
    sa.Column('preprocessing_checksum', sa.String(length=64), nullable=False),
    sa.Column('training_checksum', sa.String(length=64), nullable=False),
    sa.Column('dataset_checksum', sa.String(length=64), nullable=False),
    sa.Column('python_version', sa.String(length=20), nullable=False),
    sa.Column('library_versions', sa.JSON(), nullable=False),
    sa.Column('docker_image_digest', sa.String(length=128), nullable=True),
    sa.Column('git_commit', sa.String(length=100), nullable=True),
    sa.Column('manifest_signature', sa.String(length=64), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['model_deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_manifest_history_deployment_id'), 'deployment_manifest_history', ['deployment_id'], unique=False)
    op.create_table('deployment_replay_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_used', sa.Boolean(), nullable=False),
    sa.Column('replay_source', sa.String(length=50), nullable=False),
    sa.Column('verification_duration_ms', sa.Float(), nullable=False),
    sa.Column('verified_events', sa.Integer(), nullable=False),
    sa.Column('fallback_reason', sa.String(length=100), nullable=True),
    sa.Column('failure_class', sa.String(length=50), nullable=True),
    sa.Column('replay_confidence', sa.String(length=20), nullable=False),
    sa.Column('events_per_second', sa.Float(), nullable=False),
    sa.Column('checkpoint_load_duration_ms', sa.Float(), nullable=False),
    sa.Column('decompression_duration_ms', sa.Float(), nullable=False),
    sa.Column('replay_duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['model_deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_replay_metrics_deployment_id'), 'deployment_replay_metrics', ['deployment_id'], unique=False)
    op.create_table('deployment_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['model_deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_tags_deployment_id'), 'deployment_tags', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_tags_key'), 'deployment_tags', ['key'], unique=False)
    op.create_index(op.f('ix_deployment_tags_value'), 'deployment_tags', ['value'], unique=False)
    op.create_table('deployment_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.Integer(), nullable=False),
    sa.Column('preprocessing_version', sa.Integer(), nullable=False),
    sa.Column('training_version', sa.Integer(), nullable=False),
    sa.Column('prediction_version', sa.Integer(), nullable=False),
    sa.Column('monitoring_version', sa.Integer(), nullable=False),
    sa.Column('git_commit', sa.String(length=100), nullable=True),
    sa.Column('docker_image_digest', sa.String(length=128), nullable=True),
    sa.Column('artifact_checksum', sa.String(length=64), nullable=False),
    sa.Column('python_version', sa.String(length=20), nullable=False),
    sa.Column('library_versions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('provider_version', sa.String(length=50), nullable=True),
    sa.Column('provider_capability_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['model_deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_versions_deployment_id'), 'deployment_versions', ['deployment_id'], unique=False)
    # Custom indexes for Phase 10
    op.create_index('idx_deployments_active', 'model_deployments', ['id'], postgresql_where=sa.text("status = 'PRODUCTION'"))
    op.create_index('idx_deployments_failed', 'model_deployments', ['id'], postgresql_where=sa.text("status = 'FAILED'"))
    op.create_index('idx_approvals_active', 'deployment_approvals', ['id'], postgresql_where=sa.text("decision = 'PENDING'"))
    op.create_index('idx_locks_running', 'deployment_job_locks', ['environment_id', 'expires_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locks_running', table_name='deployment_job_locks')
    op.drop_index('idx_approvals_active', table_name='deployment_approvals')
    op.drop_index('idx_deployments_failed', table_name='model_deployments')
    op.drop_index('idx_deployments_active', table_name='model_deployments')
    op.drop_index(op.f('ix_deployment_versions_deployment_id'), table_name='deployment_versions')
    op.drop_table('deployment_versions')
    op.drop_index(op.f('ix_deployment_tags_value'), table_name='deployment_tags')
    op.drop_index(op.f('ix_deployment_tags_key'), table_name='deployment_tags')
    op.drop_index(op.f('ix_deployment_tags_deployment_id'), table_name='deployment_tags')
    op.drop_table('deployment_tags')
    op.drop_index(op.f('ix_deployment_replay_metrics_deployment_id'), table_name='deployment_replay_metrics')
    op.drop_table('deployment_replay_metrics')
    op.drop_index(op.f('ix_deployment_manifest_history_deployment_id'), table_name='deployment_manifest_history')
    op.drop_table('deployment_manifest_history')
    op.drop_index(op.f('ix_deployment_health_logs_deployment_id'), table_name='deployment_health_logs')
    op.drop_table('deployment_health_logs')
    op.drop_index(op.f('ix_deployment_events_sequence_number'), table_name='deployment_events')
    op.drop_index(op.f('ix_deployment_events_deployment_id'), table_name='deployment_events')
    op.drop_index(op.f('ix_deployment_events_current_event_hash'), table_name='deployment_events')
    op.drop_table('deployment_events')
    op.drop_index(op.f('ix_deployment_event_checkpoints_deployment_id'), table_name='deployment_event_checkpoints')
    op.drop_table('deployment_event_checkpoints')
    op.drop_index(op.f('ix_deployment_environment_variables_deployment_id'), table_name='deployment_environment_variables')
    op.drop_table('deployment_environment_variables')
    op.drop_index(op.f('ix_deployment_approvals_reviewer_id'), table_name='deployment_approvals')
    op.drop_index(op.f('ix_deployment_approvals_deployment_id'), table_name='deployment_approvals')
    op.drop_table('deployment_approvals')
    op.drop_index(op.f('ix_model_deployments_status'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_project_id'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_policy_version_id'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_model_id'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_id'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_environment_id'), table_name='model_deployments')
    op.drop_table('model_deployments')
    op.drop_table('deployment_job_locks')
    op.drop_table('deployment_settings')
    op.drop_index(op.f('ix_deployment_policies_project_id'), table_name='deployment_policies')
    op.drop_index(op.f('ix_deployment_policies_id'), table_name='deployment_policies')
    op.drop_table('deployment_policies')
    op.drop_index(op.f('ix_deployment_freeze_windows_project_id'), table_name='deployment_freeze_windows')
    op.drop_table('deployment_freeze_windows')
    op.drop_index(op.f('ix_deployment_environments_project_id'), table_name='deployment_environments')
    op.drop_index(op.f('ix_deployment_environments_id'), table_name='deployment_environments')
    op.drop_table('deployment_environments')
    # ### end Alembic commands ###
