from enum import Enum


class DatasetStatus(str, Enum):
    UPLOADING = "UPLOADING"
    UPLOADED = "UPLOADED"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    FAILED = "FAILED"
    PREPROCESSING = "PREPROCESSING"
    READY_FOR_TRAINING = "READY_FOR_TRAINING"
    ARCHIVED = "ARCHIVED"


class DatasetStage(str, Enum):
    RAW = "RAW"
    VALIDATED = "VALIDATED"
    PREPROCESSED = "PREPROCESSED"
    FEATURE_ENGINEERED = "FEATURE_ENGINEERED"
    READY_FOR_TRAINING = "READY_FOR_TRAINING"


class AlertStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


class DriftStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
